name: CI
on: pull_request

jobs:
  ubuntu-java-11:
    name: Ubuntu (Java 11)
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout phoenicis
        uses: actions/checkout@master
        with:
          name: PhoenicisOrg/phoenicis
          path: ./phoenicis
      - name: Build and install phoenicis
        run: cd ./phoenicis && mvn clean install
          
      - name: Checkout phoenicis-backend
        uses: actions/checkout@v2
        with:
          path: ./phoenicis-backend
      - name: Build phoenicis-backend
        run: cd ./phoenicis-backend && mvn clean package
